version: '3.8'

services:
  backend:
    build: .
    container_name: golang-chatapp
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - chatnet

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - chatnet

networks:
  chatnet:

volumes:
  mongo-data: